name: Build Site

on:
  push:
    branches: [ master ] 
    tags:
      - v*  
  pull_request:   

jobs:
  build:

    #Static version is used to maintain stability
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        #Static version is used to maintain stability
        node-version: [12.17.0]

    steps:
    - name: Clone the repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    # Uncomment when adding or updating dependencies in the package-lock.json
    # and package.json files for ci.
#    - name: Install Node
#      run: npm i

    # Uncomment after package-lock.json and package.json files are updated.
    - name: Run with CI
      run: npm ci

#    - name: Audit Depends
#      run: npm audit

    - name: Build Bundle
      id: build_bundle
      run: gulp bundle   
   
    - name: Set output
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
    - name: Check output
      env:
        RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
      run: |
          echo $RELEASE_VERSION
          echo ${{ steps.vars.outputs.tag }}   
    
    - name: Upload Release  
      if: contains(github.ref, 'ref/head/v*')
      uses: "marvinpinto/action-automatic-releases@latest"      
      with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "jme-ui"
          files: ./build/ui-bundle.zip           
          
    # Detects any updates to package-lock.json and package.json and commits the
    # files to root.
    # see:
    # https://github.com/marketplace/actions/add-commit?version=v4.1.0
    # for use options.
    - name: Commit Packages
      uses: EndBug/add-and-commit@v4
      with:
        message: "Commit files for CI workflow"
        # Commits these files to root if and only if there are changes.
        add: "package-lock.json package.json"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Dispatch event
      run: |
       curl -X POST https://api.github.com/repos/mitm001/docs.jmonkeyengine.org/dispatches \
       --user ${{ secrets.JME_UI_DISPATCH }} \
       --data '{"event_type":"ui-build","client_payload":{"sha": "${{ github.sha }}"}}'
